apiVersion: v1
kind: ConfigMap
metadata:
  name: rancher-demo-configmap-values
  namespace: default
data:
  values.yaml: |
    replicaCount: 2
    ingress:
      enabled: false
    service:
      type: NodePort
    app:
      localization:
        title: CONFIGMAP