apiVersion: v1
kind: Secret
metadata:
  name: rancher-demo-secret-values
  namespace: default
stringData:
  values.yaml: |
    replicaCount: 3
    ingress:
      enabled: false
    service:
      type: NodePort
    app:
      localization:
        title: SECRET