kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: nginx-backup
  namespace: app
spec:
  frequency: "@onDemand"
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - app
  actions:
    - action: backup