apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "metal-lb-config.name" . }}
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      {{- if .Values.addressPool }}
      - {{ .Values.addressPool }}
      {{- end }}
      {{- if .Values.addressPoolId }}
      - {{ index .Values.potentialPools .Values.addressPoolId }}
      {{- end }}