apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: nginx
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: web
            protocol: TCP
          env:
            - name: COW_COLOR
              value: blue
          readinessProbe:
            httpGet:
              port: web
              path: /
